[package]
name = "ocmapi"
version = "1.0.7"
edition = "2024"

[dependencies]
bytes = "1.11.1"
time = "0.3.47"
rustls-webpki = "0.103.12"
actix-web = { version = "4.13.0", features = ["openssl", "rustls-0_23"] }
config-file = "0.2.3"
rustls = "0.23.37"
serde = { version = "1.0.228", features = [ "std", "serde_derive", "derive"] }
serde_json = { version = "1.0.145", features = [ "std" ] }
actix-session = { version = "0.11.0", features = ["cookie-session"] }
actix-web-httpauth = "0.8.2"
constant_time_eq = "0.4.2"
bcrypt-pbkdf = "0.10.0"
lazy_static = "1.5.0"
chrono = "0.4.44"
gethostname = "1.1.0"
include_dir = "0.7.4"
argh = "0.1.19"
regex = "1.12.3"
rand = "0.10.1"
port_check = "0.3.0"
rustls-pki-types = "1.14.1"