[package]
name = "ocmapi"
version = "1.0.0"
edition = "2024"

[dependencies]
actix-web = { version = "4.11.0", features = ["openssl", "rustls-0_23"] }
config-file = "0.2.3"
rustls = { version = "0.23.34", features = ["aws_lc_rs"] }
rustls-pemfile = "2.2.0"
serde = { version = "1.0.228", features = [ "std", "serde_derive", "derive"] }
serde_json = { version = "1.0.145", features = [ "std" ] }
actix-session = { version = "0.11.0", features = ["cookie-session"] }
actix-web-httpauth = "0.8.2"
constant_time_eq = "0.4.2"
bcrypt-pbkdf = "0.10.0"
lazy_static = "1.5.0"
chrono = "0.4.42"
gethostname = "1.1.0"
include_dir = "0.7.4"
argh = "0.1.13"
