[package]
name = "ocmapi"
version = "1.1.4"
edition = "2024"

[dependencies]
bytes = "1.12.0"
time = "0.3.53"
rustls-webpki = "0.103.13"
actix-web = { version = "4.14.0", features = ["openssl", "rustls-0_23"] }
config-file = "0.2.3"
rustls = "0.23.41"
serde = { version = "1.0.228", features = [ "std", "serde_derive", "derive"] }
serde_json = { version = "1.0.150", features = [ "std" ] }
actix-session = { version = "0.11.0", features = ["cookie-session"] }
actix-web-httpauth = "0.8.2"
constant_time_eq = "0.5.0"
bcrypt-pbkdf = "0.11.0"
lazy_static = "1.5.0"
chrono = "0.4.45"
gethostname = "1.1.0"
include_dir = "0.7.4"
argh = "0.1.19"
regex = "1.12.4"
rand = "0.10.2"
port_check = "0.3.0"
rustls-pki-types = "1.15.0"
fake-tty = "0.3.1"
